### ISSUE TITLE
Getting STOKE ready to work on Ubuntu 16.04 and g++ version 5.3

### ISSUE THREAD

**Issue by stefanheule** [StanfordPL/stoke#887]
Necessary changes:
- g++ changed the ABI default, and pin does not compile with that, so we need to manually downgrade the ABI when compiling the pin tool.
- Change `!a & b` to `(!a) & b`.
- Add a whole bunch of `const` to x64asm.

Possibly more.

**Comment by travisdowns** [comment]
I am getting the following compiler error while running `make test` with 16.04 while using g++-4.9:

```
/tmp/ccpquy1G.o: In function `stoke::parse_regset_from_json(Json::Value)':
~/dev/stoke/././tests/cfg/cfg.h:39: undefined reference to `Json::Value::asString() const'
```

It's followed by a bunch more errors also in the Json classes. Should I assume this is covered by this issue? I didn't find a more specific issue that covers it anyway.

The initial `make` did appear to complete successfully. It's `make test` that is failing.

**Comment by bchurchill** [comment]
Yeah -- when we upgraded to 16.04 with the old compiler the jsoncpp library broke.  It's totally non-essential and your build might be fine.  There's a branch called `ubuntu16.04` which you can check out that should closely match develop, except the offensive code in the test suite is removed.  That way you can run `make test` and you'll get the majority of its benefit.

**Comment by travisdowns** [comment]
Thanks, I in the end I switched to the 16.04 branch and things seem to be going OK (other than the rep prefix illegal instruction crash).

**Comment by bchurchill** [comment]
@stefanheule Do you know how close we are to making this work?

**Comment by stefanheule** [comment]
Not really, I haven't worked on this since I last commented on this issue.  We should probably have a look at this again.

**Comment by travisdowns** [comment]
It would be nice to have 16.04 working since the master branch is getting way ahead. Eventually everyone will be on something like 16.04 or later since even the earlier releases (including LTS) will drop out of support.
